name: DCO Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DCO Sign-off Check
        uses: actions/dco@v2